# Generated by Django 5.1.2 on 2025-11-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_message_receiver_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
