# Generated by Django 5.1.2 on 2025-11-08 16:29

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_communitypost_spoiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='movie_watchlists',
            field=models.JSONField(default=myapp.models.list_for_watchlist),
        ),
        migrations.AddField(
            model_name='user',
            name='show_watchlists',
            field=models.JSONField(default=myapp.models.list_for_watchlist),
        ),
    ]
